development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  pool: 5
  username: sample
  password:
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  pool: 5
  username: sample
  password:
  host: localhost
